#name: Release Version
#
#on:
#  push:
#    tags:
#      - 'v*.*.*'
#
#jobs:
#  add-version-tag:
#    runs-on: ubuntu-latest
#    steps:
#      - id: version
#        uses: battila7/get-version-action@v2
#      - name: Add Semantic Version tag to Docker Image
#        uses: shrink/actions-docker-registry-tag@v3
#        with:
#          registry: ghcr.io
#          repository: '${{ github.repository }}'
#          target: 'sha-${{ github.sha }}'
#          tags: '${{ steps.version.outputs.version }}'